# Generated by Django 3.1.7 on 2021-03-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210317_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='important',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
