# Generated by Django 3.1.7 on 2021-03-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_tickets_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
