# Generated by Django 3.1.7 on 2021-03-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210318_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
