# Generated by Django 3.1.7 on 2021-03-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
