# Generated by Django 3.1.7 on 2021-09-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('end_time', models.DateTimeField(auto_created=True, blank=True)),
                ('start_time', models.DateTimeField(auto_created=True, blank=True)),
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('logger', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
