# Generated by Django 3.1.7 on 2021-03-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
