# Generated by Django 3.1.7 on 2021-09-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='end_time',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
