# Generated by Django 3.1.7 on 2021-03-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='user_profile',
        ),
    ]
