# Generated by Django 3.1.7 on 2021-03-15 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_profile_email'),
        ('structure', '0005_auto_20210315_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.user_profile'),
        ),
    ]
