# Generated by Django 3.1.7 on 2021-04-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_auto_20210315_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(help_text='This is the grey text', max_length=14),
        ),
    ]
