# Generated by Django 3.1.7 on 2021-03-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
