# Generated by Django 3.1.7 on 2021-03-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20210323_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='facilities',
            field=models.CharField(default='Nan', max_length=50),
        ),
    ]
