# Generated by Django 3.1.7 on 2021-03-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_rooms_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_image',
            field=models.ImageField(blank=True, upload_to='rooms'),
        ),
    ]
