# Generated by Django 3.1.7 on 2021-03-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_rooms_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.TextField(default='today', max_length=10),
        ),
    ]
